### ISSUE TITLE
Starter Characters Reset

### ISSUE THREAD

**Issue by cryptidm0th** [AguzzTN54/Genshin-Impact-Wish-Simulator#11]
I do not close out of the tab for the Genshin pulling website, but occasionally if I close my laptop and come back, I all of a sudden do not have Kaeya, Lisa, or Amber anymore. I find this strange since it is just the beginner characters. It really isn't that big of a deal, just thought I'd bring light to it.

**Comment by AguzzTN54** [comment]
Did you really make sure that you got the starter character?
Beginner characters can only be obtained in Standard Banner, so you won't have them if you haven't pulled the standard banner

**Comment by cryptidm0th** [comment]
I'm sure. I got c6 Kaeya using standard banner and next thing I know it's
gone.

**Comment by AguzzTN54** [comment]
when did you get them? I've updated the site several times, if you pulled it a month ago, maybe some history has been deleted by the system. 

or are you sure you didn't pull them at a different site, I have deployed this simulator on [wishsimulator.vercel.app](wishsimulator.vercel.app) and [wishsimulator-genshin.vercel.app](wishsimulator-genshin.vercel.app) you can check both to make sure again.

As you know, the site use LocalStorage to save pull history, if you clear your browser data, this site data will be deleted too.
I can't reproduce the problem that happen to you right now, most likely this happens because of clients/users or browser actions.
I will fix it once I find out the details of the problem and the cause. Btw Thanks for your feedback, please enjoy the Simulator.
