### ISSUE TITLE
Adding it-IT.json for Items

### ISSUE THREAD

**Issue by ScarletSeal** [AguzzTN54/Genshin-Impact-Wish-Simulator#70]
[it-IT.zip](https://github.com/AguzzTN54/Genshin-Impact-Wish-Simulator/files/10951806/it-IT.zip)

Note: Mika's in there too, idk if that could cause you any problems.

**Comment by AguzzTN54** [comment]
Since you can do a development, I thought it would be better if you create a pull request for this.
If I add it manually, your contribution won't be recorded by Github.

Just insert your locale name into `itemLocales` in `/src/lib/helpers/i18n.js` after putting the json file into `src/locales/items/` folder
https://github.com/AguzzTN54/Genshin-Impact-Wish-Simulator/blob/d3674468fd112d7793743bd1e0e6995ca92e0298/src/lib/helpers/i18n.js#L16

However, if you don't have a problem with this, I'll add it myself.
